// Module included in the following assemblies:
//
// assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: CONCEPT
[id="con_about-scheduling-importer-pods_{context}"]
= About scheduling importer pods

[role="_abstract"]
{project-full} uses `virt-v2v` convertor pods, or _importer pods_, to transfer data from VMware source virtual machines (VMs) to target VMs. 

By default, {virt} assigns the nodes to which these importer pods transfer data. However, for migrations from VMware VMs, you can schedule the destination nodes for the importer pods.

[IMPORTANT]
====
Scheduling importer pods is supported only for migrations from VMware.
====

* For migrations via the command-line, schedule the importer pods in the `Plan` CR, as described in {mtv-mig}assembly_migrating-from-vmware_mtv#proc_migrating-vms-cli-vmware_vmware[Running a {vmw} vSphere migration from the command-line].
* For migration via the UI, schedule the importer pods on the *Plan settings* page, as described in xref:proc_configuring-plan-settings-vmware_{context}[Configuring VMware migration plan settings].

