// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_migrating-vms-web-console.adoc

:_mod-docs-content-type: CONCEPT
[id="con_migrating-vms-by-using-mtv-ui_{context}"]

= Migrating virtual machines by using the MTV user interface

[role="_abstract"]
Use the {project-short} user interface to migrate virtual machines (VMs) from the following providers:

* VMware vSphere
* {rhv-full} ({rhv-short})
* {osp}
* Open Virtual Appliances (OVAs) that were created by VMware vSphere
* {virt} clusters

For all migrations, you specify the source provider, the destination provider, and the migration plan. The specific procedures vary per provider.

[IMPORTANT]
====
You must ensure that all prerequisites are met. For more information, see link:{mtv-plan}assembly_software-requirements-for-migration_mtv[Software requirements for migration].

VMware only: You must have the minimal set of link:{mtv-plan}assembly_provider-specific-requirements-for-migration_mtv#vmware-privileges_mtv[VMware privileges].

VMware only: Creating a link:{mtv-plan}assembly_provider-specific-requirements-for-migration_mtv#proc_creating-vddk-image_mtv[VMware Virtual Disk Development Kit (VDDK)] image increases migration speed.
====

