
ifdef::context[:parent-context: {context}]

:_mod-docs-content-type: ASSEMBLY

[id="assembly_migrating-vms-web-console_{context}"]

= Migrating virtual machines by using the {ocp} web console

//:context: migrating-vms-web

[role="_abstract"]

Use the {project-short} user interface to migrate virtual machines (VMs) from VMware vSphere, {rhv-full} ({rhv-short}), {osp}, Open Virtual Appliances (OVAs) that were created by VMware vSphere, or {virt} clusters. For all migrations, you specify the source provider, the destination provider, and the migration plan. The specific procedures vary per provider.

[IMPORTANT]
====
You must ensure that all prerequisites are met. For more information, see link:{mtv-plan}assembly_software-requirements-for-migration_mtv[Software requirements for migration].

VMware only: You must have the minimal set of link:{mtv-plan}vmware-privileges_mtv[VMware privileges].

VMware only: Creating a link:{mtv-plan}assembly_provider-specific-requirements-for-migration_mtv#proc_creating-vddk-image_mtv[VMware Virtual Disk Development Kit (VDDK)] image will increase migration speed.
====

include::../modules/con_navigating-mtv-pages.adoc[leveloffset=+1]

include::../modules/con_mtv-ui.adoc[leveloffset=+1]

include::../modules/con_mtv-overview-page.adoc[leveloffset=+1]

include::../modules/proc_choosing-different-controller-transfer-network.adoc[leveloffset=+2]

include::../modules/con_preparing-vms-for-migration.adoc[leveloffset=+1]

include::../modules/proc_renaming-vms-for-migration.adoc[leveloffset=+2]

include::../modules/proc_configuring-target-power-state-vms.adoc[leveloffset=+2]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]




